local set = vim.opt

set.exrc = true
set.relativenumber = true
set.nu = true
set.hlsearch = false
set.hidden = true
set.errorbells = false
set.tabstop = 4
set.softtabstop = 4
set.shiftwidth = 4
set.expandtab = true
set.smartindent = true
set.wrap = false
set.incsearch = true
set.scrolloff = 8
set.updatetime = 50
set.signcolumn = 'number'
set.termguicolors = true
set.timeoutlen = 100
